export const facilities = [
  'Chippewa Valley Correctional Treatment Facility',
  'Columbia Correctional Institution',
  'Dodge Correctional Institution',
  'Fox Lake Correctional Institution',
  'Green Bay Correctional Institution',
  'Jackson Correctional Institution',
  'Kettle Moraine Correctional Institution',
  'Milwaukee Secure Detention Facility',
  'New Lisbon Correctional Institution',
  'Oakhill Correctional Institution',
  'Oshkosh Correctional Institution,',
  'Prairie du Chien Correctional Institution',
  'Racine Correctional Institution',
  'Racine Youthful Offender Correctional Facility',
  'Redgranite Correctional Institution',
  'Stanley Correctional Institution',
  'Sturtevant Transitional Facility',
  'Waupun Correctional Institution',
  'Wisconsin Secure Program Facility',
  'Black River Correctional Center',
  'Drug Abuse Correctional Center',
  'Felmers O. Chaney Correctional Center',
  'Flambeau Correctional Center',
  'Gordon Correctional Center',
  'John C. Burke Correctional Center',
  'Kenosha Correctional Center',
  'Marshall E. Sherrer Correctional Center',
  'McNaughton Correctional Center',
  'Oregon Correctional Center',
  'Sanger B. Powers Correctional Center',
  'St. Croix Correctional Center',
  'Thompson Correctional Center',
  'Winnebago Correctional Center',
  'Taycheedah Correctional Institution',
  "Milwaukee Women's Correctional Center",
  'Robert E. Ellsworth Correctional Center',
  'Community Reintegration Center (CRC)',
];
