export enum Support {
  employment = 'employment',
  housingResources = 'housingResources',
  financialManagement = 'financialManagement',
  familyCounseling = 'familyCounseling',
  transportation = 'transportation',
  healthcareServices = 'healthcareServices',
  religionSpirituality = 'religionSpirituality',
  drugAlcoholCounseling = 'drugAlcoholCounseling',
  lifeCoaching = 'lifeCoaching',
  businessStartup = 'businessStartup',
  driversLicenceStateId = 'driversLicenceStateId',
  resume = 'resume',
  childCare = 'childCare',
  ongoingEducation = 'ongoingEducation',
  foodAssistance = 'foodAssistance',
  basicTechSkills = 'basicTechSkills',
  cellPhoneResources = 'cellPhoneResources',
  softSkillsTraining = 'softSkillsTraining',
  legalResources = 'legalResources',
  basicHygieneSupport = 'basicHygieneSupport',
  clothing = 'clothing',
  mentalHealth = 'mentalHealth',
  veteranSupport = 'veteranSupport',
  domesticViolence = 'domesticViolence',
  vocationalTraining = 'vocationalTraining',
  gedHsed = 'gedHsed',
}

export const supportText = {
  [Support.employment]: 'Employment',
  [Support.housingResources]: 'Housing Resources',
  [Support.financialManagement]: 'Financial Management',
  [Support.familyCounseling]: 'Family Counseling',
  [Support.transportation]: 'Transportation',
  [Support.healthcareServices]: 'Healthcare Services',
  [Support.religionSpirituality]: 'Religion / Spirituality',
  [Support.drugAlcoholCounseling]: 'Drug / Alcohol Counseling',
  [Support.lifeCoaching]: 'Life Coaching',
  [Support.businessStartup]: 'Business Startup',
  [Support.driversLicenceStateId]: 'Drivers Licence and / or State ID',
  [Support.resume]: 'Resume',
  [Support.childCare]: 'Child Care',
  [Support.ongoingEducation]: 'Ongoing Education',
  [Support.foodAssistance]: 'Food Assistance',
  [Support.basicTechSkills]: 'Basic Tech Skills',
  [Support.cellPhoneResources]: 'Cell Phone Resources',
  [Support.softSkillsTraining]: 'Soft Skills Training',
  [Support.legalResources]: 'Legal Resources',
  [Support.basicHygieneSupport]: 'Basic Hygiene Support',
  [Support.clothing]: 'Clothing',
  [Support.mentalHealth]: 'Mental Health',
  [Support.veteranSupport]: 'Veteran Support',
  [Support.domesticViolence]: 'Domestic Violence',
  [Support.vocationalTraining]: 'Vocational Training',
  [Support.gedHsed]: 'GED/HSED',
};
