export enum VeteranBranchOfService {
  usArmy = 'usArmy',
  usMarineCorps = 'usMarineCorps',
  usNavy = 'usNavy',
  usAirForce = 'usAirForce',
  usSpaceForce = 'usSpaceForce',
  usCoastGuard = 'usCoastGuard',
}

export enum VeteranRank {
  AB = 'AB',
  PVT = 'PVT',
  SR = 'SR',
  Amn = 'Amn',
  PV2 = 'PV2',
  SA = 'SA',
  A1C = 'A1C',
  LCpl = 'LCpl',
  PFC = 'PFC',
  SN = 'SN',
  CPL = 'CPL',
  PO3 = 'PO3',
  SrA = 'SrA',
  SPC = 'SPC',
  PO2 = 'PO2',
  SGT = 'SGT',
  SSgt = 'SSgt',
  PO1 = 'PO1',
  SSG = 'SSG',
  TSgt = 'TSgt',
  CPO = 'CPO',
  GySgt = 'GySgt',
  MSgt = 'MSgt',
  SFC = 'SFC',
  e81stSgt = 'e81stSgt',
  MSG = 'MSG',
  SCPO = 'SCPO',
  SMSgt = 'SMSgt',
  CMSgt = 'CMSgt',
  CCM = 'CCM',
  CMCPO = 'CMCPO',
  CSM = 'CSM',
  e91stSgt = 'e91stSgt',
  MCPO = 'MCPO',
  MGySgt = 'MGySgt',
  SGM = 'SGM',
  ENS = 'ENS',
  '1LT' = '1LT',
  '2LT' = '2LT',
  ADM = 'ADM',
  GEN = 'GEN',
  '1stLt' = '1stLt',
  LTJG = 'LTJG',
  CPT = '',
  LT = 'LT',
  LCDR = 'LCDR',
  MAJ = 'MAJ',
  CDR = 'CDR',
  LTC = 'LTC',
  COL = 'COL',
  CAPT = 'CAPT',
  BG = 'BG',
  MG = 'MG',
  RDML = 'RDML',
  LTG = 'LTG',
  VADM = 'VADM',
  WO1 = 'WO1',
  CW2 = 'CW2',
  CW3 = 'CW3',
  CW4 = 'CW4',
  CW5 = 'CW5',
}

export enum VeteranCampaign {
  wwii = 'wwii',
  korea = 'korea',
  vietnam = 'vietnam',
  gulfWar = 'gulfWar',
  bosnia = 'bosnia',
  kosovo = 'kosovo',
  oef = 'oef',
  oif = 'oif',
  inherentResolve = 'inherentResolve',
}

export enum VeteranTypeDischarge {
  honorable = 'honorable',
  general = 'general',
  oth = 'oth',
  bcd = 'bcd',
  dishonorable = 'dishonorable',
  entryLevelSeparation = 'entryLevelSeparation',
  medicalSeparation = 'medicalSeparation',
  separationGovernmentConvenience = 'separationGovernmentConvenience',
}
