import {
  Age,
  ClientCaseManager,
  ClientType,
  Ethnicity,
  Experience,
  Gender,
  Job,
  JobSalaries,
  JobStatus,
  JusticeStatus,
  MaritalStatus,
  OffenseCategory,
  OffenseCategoryType,
  Orientation,
  ReferredBy,
  ReleasedAt,
  Religion,
  RspAccountType,
  RspClient,
  RspClientStatus,
  RspInvitation,
  RspPosition,
  RspRole,
  RspType,
  State,
  StateFederal,
  Support,
  TimeServed,
  TypeOfWork,
  VeteranBranchOfService,
  VeteranCampaign,
  VeteranOrJustice,
  VeteranRank,
  VeteranStatus,
  VeteranTypeDischarge,
  WorkingTime,
} from '@two/shared';
import { User, UserType } from '@app/api';

export const rsp: RspType = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06h',
  name: 'Employ Milwaukee',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  address: '1010 Maple Dr',
  city: 'West Allis',
  state: State.WI,
  postalCode: '53227',
  phone: '3101231234',
  email: 'hello@em.com',
  servicesArea: ['County Name'],
  support: [Support.employment],
  justiceStatus: [JusticeStatus.freeWorld, JusticeStatus.halfwayHouse],
  offenses: [OffenseCategory.possession, OffenseCategory.burglary],
  veteranOrJustice: [VeteranOrJustice.justiceImpacted],
};

export const client: ClientType & { id: string } = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06c',
  veteranOrJustice: [VeteranOrJustice.justiceImpacted],
  firstName: 'Test',
  lastName: 'User',
  email: 'test@example.com',
  justiceStatus: JusticeStatus.freeWorld,
  address: '111 Street',
  city: 'Los Angeles',
  state: State.CA,
  postalCode: '90887',
  support: [Support.resume],
  gender: Gender.female,
  orientation: Orientation.heterosexual,
  religion: Religion.christianity,
  maritalStatus: MaritalStatus.single,
  age: Age['16-24'],
  disability: false,
  ethnicity: Ethnicity.eastAsian,
  veteranStatus: VeteranStatus.notVeteran,
  referredBy: ReferredBy.familyFriends,
  personalStrengths: [],
  experience: [],
  languages: [],
  offense: [OffenseCategory.arson],
  sexualOffenderRegistry: false,
  sbn: false,
  timeServed: TimeServed.timeServed01,
  releasedAt: ReleasedAt.releasedAt01,
  stateOrFederal: StateFederal.federal,
  relativeExperience: [],
  personalSummary: 'personal summary',
  education: [],
  license: [],
  updatedAt: new Date('2023-01-01T00:00:00.000Z'),
};

export const veteranAndJusticeImpactedClient: ClientType & { id: string } = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06c',
  veteranOrJustice: [VeteranOrJustice.justiceImpacted, VeteranOrJustice.veteran],
  firstName: 'Test',
  lastName: 'User',
  email: 'test@example.com',
  address: '111 Street',
  city: 'Los Angeles',
  state: State.CA,
  postalCode: '90887',
  support: [Support.resume],
  gender: Gender.female,
  orientation: Orientation.heterosexual,
  religion: Religion.christianity,
  maritalStatus: MaritalStatus.single,
  age: Age['16-24'],
  disability: false,
  ethnicity: Ethnicity.eastAsian,
  veteranStatus: VeteranStatus.notVeteran,
  referredBy: ReferredBy.familyFriends,
  personalStrengths: [],
  experience: [],
  languages: [],
  relativeExperience: [],
  personalSummary: 'personal summary',
  education: [],
  license: [],
  updatedAt: new Date('2023-01-01T00:00:00.000Z'),
  veteranReservist: false,
  veteranService: [VeteranBranchOfService.usAirForce],
  veteranRank: VeteranRank['1stLt'],
  veteranStartAt: '2000-05-01',
  veteranCampaigns: [VeteranCampaign.gulfWar],
  veteranTypeDischarge: VeteranTypeDischarge.general,
  veteranDd214: false,
  justiceStatus: JusticeStatus.freeWorld,
  offense: [OffenseCategory.arson],
  sexualOffenderRegistry: false,
  sbn: false,
  timeServed: TimeServed.timeServed01,
  releasedAt: ReleasedAt.releasedAt01,
  stateOrFederal: StateFederal.federal,
};

export const veteranClient: ClientType & { id: string } = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06c',
  veteranOrJustice: [VeteranOrJustice.veteran],
  firstName: 'Test',
  lastName: 'User',
  email: 'test@example.com',
  address: '111 Street',
  city: 'Los Angeles',
  state: State.CA,
  postalCode: '90887',
  support: [Support.resume],
  gender: Gender.female,
  orientation: Orientation.heterosexual,
  religion: Religion.christianity,
  maritalStatus: MaritalStatus.single,
  age: Age['16-24'],
  disability: false,
  ethnicity: Ethnicity.eastAsian,
  veteranStatus: VeteranStatus.notVeteran,
  referredBy: ReferredBy.familyFriends,
  personalStrengths: [],
  experience: [],
  languages: [],
  relativeExperience: [],
  personalSummary: 'personal summary',
  education: [],
  license: [],
  updatedAt: new Date('2023-01-01T00:00:00.000Z'),
  veteranReservist: false,
  veteranService: [VeteranBranchOfService.usAirForce],
  veteranRank: VeteranRank['1stLt'],
  veteranStartAt: '2000-05-01',
  veteranCampaigns: [VeteranCampaign.gulfWar],
  veteranTypeDischarge: VeteranTypeDischarge.general,
  veteranDd214: false,
};

export const user: User = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06f',
  firstName: 'Test',
  lastName: 'User',
  email: 'test@example.com',
  type: UserType.Client,
  createdAt: '2020-01-01T00:00:00.000Z',
  updatedAt: '2020-01-01T00:00:00.000Z',
  client,
};

export const job: Job = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06g',
  title: 'Car Wash Attendant',
  description:
    'Wash attendants are responsible for performing the daily operational practices of running the car wash facility.',
  department: 'Customer Service',
  startDate: '12.2024',
  typeOfWork: TypeOfWork.hybrid,
  workingTime: WorkingTime.fullTime,
  experience: Experience.mid,
  numberOfOpenPositions: 3,
  offenses: [OffenseCategory.arson],
  responsibilities: [],
  skillsDescription:
    "The most successful and happy people have PMA – a Positive Mental Attitude! We are a huge believer in putting attitude above aptitude. We can always teach you how to do the job, but we can't teach a Positive Mental Attitude... You either have it or you don't!",
  salaryOptions: {
    salary: JobSalaries.hourly,
    min: '15',
    max: '30',
    description:
      'Starting wage is $13 per hour + tips, with an Employer Bonus after positive a 90 Day Review (provided by the employer)',
    bonuses: ['Additional $100 Bonus for Positive 90 Day Review'],
  },
  applications: [],
  createdAt: new Date('2023-01-01T00:00:00.000Z'),
  updatedAt: new Date('2023-01-01T00:00:00.000Z'),
  status: JobStatus.active,
  applicationsCount: 0,
  offensesTypes: [OffenseCategoryType.propertyDamage],
  veteranOrJustice: [VeteranOrJustice.veteran, VeteranOrJustice.justiceImpacted],
};

export const rspAccountMember: RspAccountType = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06i',
  firstName: 'Leonard',
  lastName: 'Krasner',
  phone: '1231231234',
  email: 'leonard.k@example.com',
  role: RspRole.member,
  position: RspPosition.caseManager,
  isProfileFilled: true,
  userId: '10b8b8cf-601b-475b-ba0b-a05bc9a3a06i',
  rspId: rsp.id,
  rsp,
  caseLoad: 1,
};

export const rspAccountOwner: RspAccountType = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a07i',
  firstName: 'Leonard',
  lastName: 'Krasner',
  phone: '1231231234',
  email: 'leonard.k@example.com',
  role: RspRole.owner,
  position: RspPosition.hrDirector,
  isProfileFilled: true,
  userId: '10b8b8cf-601b-475b-ba0b-a05bc9a3a07i',
  rspId: rsp.id,
  rsp,
};

export const rspClient: RspClient = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a08i',
  status: RspClientStatus.pending,
  rspId: rsp.id,
  userId: user.id,
  user,
};

export const rspClient2: RspClient = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a08j',
  status: RspClientStatus.active,
  rspId: rsp.id,
  userId: '10b8b8cf-601b-475b-ba0b-a05bc9a3a04g',
  user: { ...user, id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a04g', email: 'test1@example.com' },
};

export const clientCaseManager: ClientCaseManager = {
  firstName: 'FirstName',
  lastName: 'LastName',
  email: 'test@test.com',
  rspName: 'Name',
};

export const invitation: RspInvitation = {
  id: '10b8b8cf-601b-475b-ba0b-a05bc9a3a03i',
  firstName: 'First',
  lastName: 'Last',
  email: 'first.last@email.com',
  phone: '3342223333',
  rspId: rsp.id,
};

export const statistics = {
  result: {
    basicHygieneSupport: 1,
    basicTechSkills: 2,
    childCare: 1,
    clothing: 1,
  },
  total: 6,
};
